### PR TITLE
Fix encoding of blob data type in CDT list/map bins

### LINKED ISSUE #84: Encoding error (undefined conversion error) while reading digests.
When I try to get the bins of a set which contains an array of digest of another set, it throws me an encoding error. Following is an example:

```
require "aerospike"

@client = Aerospike::Client.new('127.0.0.1:3000')

key_1 = Aerospike::Key.new('NS1', 'names', "123")

record = { 'name' => "Apurva Mayank" }

@client.put(key_1, record)

digest = Aerospike::BytesValue.new(key_1.digest)

key_2 = Aerospike::Key.new('NS1', 'city', "456")

record = { 'city' => "pune", "names" => [digest] }

@client.put(key_2, record)

@client.get(key_2)
```
The last line in the above code snippet throws **Encoding::UndefinedConversionError ("\x9E" from ASCII-8BIT to UTF-8)** error.

**force_encoding** in **normalize_elem** method in **unpacker.rb** seems one solution to it. I am trying to find if there is any other way to it as well.

### PR DESCRIPTION
**Pull request by jhecking**
Resolves #84.

### CODE REVIEW

File: lib/aerospike/utils/unpacker.rb [hunk 1]
```diff
@@ -85,7 +85,12 @@ def unpack_map(hash)
     def normalize_elem(elem)
       case elem
       when String
-       elem[1..-1].encode(Aerospike.encoding)
+        ptype = elem.ord
+        value = elem[1..-1]
+        if (ptype == ParticleType::STRING)
```
Comment (apurvamayank) [inline lib/aerospike/utils/unpacker.rb]: I think this should be as below
```suggestion
        if (ptype == Aerospike::ParticleType::STRING)
```

Comment (jhecking) [reply lib/aerospike/utils/unpacker.rb]: `Aerospike::Unpacker` and `Aerospike::ParticleType` are on the same level of the module hierarchy, so the `Aerospike::` namespace can be omitted.
